### PR TITLE
Quality of life Improvements

### PR DESCRIPTION
**Pull request by Tx-ID**

### CODE REVIEW

**Comment by HalizaSyafa27** [comment]
gooddd!!!

**Review by HalizaSyafa27 — COMMENTED** [review]
good!!

**Review by HalizaSyafa27 — APPROVED** [review]
good code nya sgt bermanfaat thx

**Review by Tx-ID — COMMENTED** [review]
a

**Comment by Gilangk1902** [comment]
OMAYGAT

**Pull request merged**
